# These are supported funding model platforms

# GitHub Sponsors (if you have one set up)
# github: yourusername

# Custom donation links
custom:
  - https://etherscan.io/address/0x618d855C2F32f1C9343624111b8bEd20eEccdf53

# Ethereum address for direct donations
# ETH/ERC-20/Polygon/Base/Arbitrum: 0x618d855C2F32f1C9343624111b8bEd20eEccdf53
